### ISSUE TITLE
Why scala

### ISSUE THREAD

**Issue by SoloDevOG** [twitter/the-algorithm#10]
Why scala?

**Comment by Element115Studios** [comment]
Did you expect Twitter engineers to pick anything good?

**Comment by fidelmak** [comment]
They ought to

**Comment by gokhaneryigit** [comment]
https://github.com/twitter/the-algorithm-ml

**Comment by joan38** [comment]
@Element115Studios Do you expect Tesla engineers to pick anything good?

**Comment by joan38** [comment]
@SoloDevOG Because Scala is a functional programming language with strong typing. Scala's language features have been proven right looking at how other languages are picking up (Java lambdas, record classes, record decomposition...; Typing for Javascript with TypeScript...)

![image](https://user-images.githubusercontent.com/1200478/229260335-0cafa850-10cc-4264-b0bf-3f0597389ce3.png)

**Comment by lemystic** [comment]
Scala is used for building data-intensive, distributed applications and systems
