### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by algonacci** [twitter/the-algorithm#1433]
Why Scala? Is it because of FP?

**Comment by KennethCho-CKH** [comment]
Yes, FP is one of the big reason why they use Scala as they have a complex algorithm, Scala also offers excellent support for concurrency and parallelism, and also highly expressive, which can help improve the performance and scalability of Twitter's algorithms (It is called Scala because of it's scalability). And it uses JVM, so it can use tools from Java. There are many reason and these are the main points.

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
