### ISSUE TITLE
If this is licensed AGPL 3.0, does Twitter need to release it's entire Source Code?

### ISSUE THREAD

**Issue by MrHPotter** [twitter/the-algorithm#1588]

**Comment by jtbx** [comment]
I don't think so. The AGPL says any derivatives, running as a network service or not, has to be licensed under itself (the AGPL). The source code in this repository is the code behind the recommendation algorithm for twitter.com, and the algorithm only. This means they don't need to release all their source code running on twitter.com because it's not a derivative of this software, the rest of twitter.com is its own software.

**Comment by tauraamui** [comment]
Also the authors of works under the GPL are not themselves subject to the GPL. Licenses apply only to third parties, not the author themselves.

**Comment by MrHPotter** [comment]
Ok thanks, obvious, when i think about it, as they are the one protectkng the product of their work.

**Comment by PickleNik** [comment]
also dup #404
