### ISSUE TITLE
Add Dislikes so I can Dislike people Disliking Elons Tweets while I Dislike Elons Tweets

### ISSUE THREAD

**Issue by Floofbutt** [twitter/the-algorithm#1607]
Everybody wins.

**Comment by LeBeDevCode** [comment]
Hm. That's make sense

**Comment by logicP** [comment]
Honestly I kinda wish that downvotes to get content removed or hidden that shouldn't be there was more of a thing, but I also understand that in this day and age of the internet it would get abused on a site like Twitter if implemented poorly. So if something like that were implemented I would make it so that the user has a limited amount of downvotes on content that they see and they have to wait after a time for them to be able to use more.

Also, once you spend your downvote on one piece of content you can't do it again to the same piece of content to prevent more abuse, incentivizing people to choose wisely. Of course, that would require an entire overhaul of Twitter altogether, which likely will never happen unless the entire website were to go completely open source and Elon is no longer in charge

**Comment by Ivaylo-Korakov** [comment]
We need that

**Comment by Angus1811** [comment]
how is this unrelated 

im not joking this time we acc need this feature so elon can release how bad his twitter is

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
