### ISSUE TITLE
suggest to group individuals based on IQ-levels

### ISSUE THREAD

**Issue by a-recent-converter-to-mullvadianism** [twitter/the-algorithm#1782]
dont bubble ppl into a group of ppl who think like them, let the high-IQ ppl debate complex ideas from opposite camps with each other, but keep those discussions away from low-IQ ppl where they misinterpret the tweet and have low reading comprehension

also in search/trending, let me find convos that are really high-IQ/engaging and interesting, not the useless stuff that shows up rn.

**Comment by devkvlt** [comment]
And how should we go about measuring the IQ of Twitter users?

**Comment by a-recent-converter-to-mullvadianism** [comment]
my suggestion would be that there needs to be some sort of algo to spot repetitive low reading comprehension based on tweets/reply's to tweets (not just swearing like rn, as that's not a good indicator on its own) and suggest other users to them that also do the same, despite ideological beliefs.

And put ppl together that have a good avg of directly addressing a tweet with insight(despite low/high follower count) as that can be a good incentive for good faith arguments and be indicative of a higher IQ

**Comment by devkvlt** [comment]
IQ is a complex construct that involves various cognitive abilities such as reasoning, problem solving, and critical thinking, etc. It's virtually impossible to assess these abilities based on tweets.. I can't even remember the last time I've seen a tweet that holds any intellectual value.

And determining who has good "reading comprehension" and who doesn't is subjective and may lead to arbitrary and unfair categorization.

Instead, the solution to the problem you brought up is to simply provide tools to report and **address** abusive and harmful behavior.

Rather than putting together people of the same **subjectively perceived level of intelligence**, we should put together people based on their **objectively determined interests**. Unfortunately, last time I checked, Twitter sucked at this.

**Comment by a-recent-converter-to-mullvadianism** [comment]
thats fair, it does seem very hard to assess anyways based on tweets
