### ISSUE TITLE
author is elon !!!

### ISSUE THREAD

**Issue by mazidan77** [twitter/the-algorithm#436]
"author_is_elon",
      candidate =>
        candidate
          .getOrElse(AuthorIdFeature, None).contains(candidate.getOrElse(DDGStatsElonFeature, 0L))),

**Comment by cs3c** [comment]
Long live Elon

**Comment by yzhuang** [comment]
Based on the code, it was only used to measure serving statistics via Twitter's A/B testing framework, and this “is_author_elon” feature does not impact the recommendation algorithm.

**Comment by Lamby777** [comment]
> Weirdly, they didn’t clean it up before open-sourcing the code but did it after open-sourcing the code.

Probably just lumped it in with the democrats/republicans removal just to be safe.

**Comment by harish-datla** [comment]
> ct the recommendation algorithm.

it impacts the recommendation algorithm, because if you read the whole comment , it clearly says, changes that negatively affect one over the other in the four groups will not be pushed. So basically developer created a category for elon besides democrats, republicans and VIT's to make sure that his tweets are not deboosted compared to other three categories with any new change push. So any new changes to recommendation algorithm that got pushed after this changes got  introduced gives a huge boost to his tweets than before
