### ISSUE TITLE
Addressing Hate Speech and Harassment on Twitter

### ISSUE THREAD

**Issue by 0xEbrahim** [twitter/the-algorithm#515]
Twitter is an important social media platform that connects millions of people around the world. However, a persistent issue on the platform is the prevalence of hate speech and harassment. Despite efforts to address this issue, many users still encounter abusive content and behavior that can have a negative impact on their experience on the platform.

The current policies and tools in place to combat hate speech and harassment on Twitter are a step in the right direction, but they may not be enough to fully address the problem. Some users feel that the reporting and enforcement processes can be slow and ineffective, allowing abusive content and behavior to persist. Additionally, the definition of hate speech can be ambiguous, leading to inconsistent enforcement of policies.

To address this issue, Twitter could consider implementing the following measures:

Improve the reporting process for abusive content and behavior, making it easier and faster for users to report and for Twitter to take action.

Increase transparency and consistency in the enforcement of hate speech policies, providing clear guidelines on what constitutes hate speech and ensuring that policies are consistently applied.

Invest in technology and resources to better detect and remove hate speech and harassment, including the use of machine learning and AI.

Provide better support for users who have been affected by hate speech and harassment, including access to counseling and other resources.

By taking these measures, Twitter can create a safer and more inclusive platform for all users, and ensure that hate speech and harassment are not tolerated.

**Comment by 0xEbrahim** [comment]
LoL , i think guys liked this env XD

**Comment by sagehawk** [comment]
The problem with hate speech is that it's not helpful. For the betterment of the Twitter experience, we need a solution for hatespeech and harassment. I had a similar issue posted provided with a solution that may align with a solution you could be looking for: https://github.com/twitter/the-algorithm/issues/538

**Comment by satmuts** [comment]
there is no such thing "hate speech"
there is only "speech people hate"

**Comment by tessarion87** [comment]
Allegedly, one of the social media giants--might've been Twitter, might've been Facebook, can't remember which--had a pretty effective algorithm for detecting and removing hate speech on their platform.

Unfortunately, it got scrapped when it was discovered that a lot of right-wing pundits and politicians' posts were recognized as hate speech, and, alas, that was the end of that.

Honestly, they should bring that filter back.

**Comment by HazelDomain** [comment]
Currently reports for “this user is encouraging someone else to kill themselves” and “this user is threatening to commit suicide” both go through the same process, so after reporting someone for suibaiting, Twitter support reassures you that they’ve reached out to the person you reported ‘to let them know someone cares about them uwu’ 

That kind of nonsense seems like an easy fix but idk.

**Comment by nikolqy** [comment]
Imagine taking this area seriously. All of the issues created are shitposts. It's not that deep

**Comment by ValZapod** [comment]
Just wanted to say. If I use the n-word on twitter I put a space between first letter and second. So...

![Screenshot_20230401_061547_Twitter](https://user-images.githubusercontent.com/31514790/229263138-00cf7aab-ee50-4f4e-8bc5-fed4428407dd.png)

**Comment by ldmtwo** [comment]
Suggestion: Optional (default to opt out of harsh content) filtering of this. Keep hate speech in the public so we know who they are, but enable filtering by default. There are many models with sentiment that work well. I don't care if people cypher letters like L0s3rϟ. It's easy to decipher those. No excuse for not being able to filter the easy ones.

**Comment by Sqaaakoi** [comment]
keep AI moderation out of hate-speech land unless it's VERY confident on what is hate speech
also hate speech is subjective and elon has negative biases against some minorities and actively supports that hate speech
leave hellsite if you don't like hate speech

**Comment by darkdevildeath** [comment]
First, we need to reach a formal consensus on the definition of hate speech as this is controversial.

For example, is defending Stalin hate speech? Is defending the agenda of self-declared communist politicians and dictators hate speech? Is defending Christianity hate speech? For me yes. For the little friend next door, maybe not.

(I don't really think so, it's just an allegory.)

Then we have to find out what causes it. And demonstrate the causal link through systematically reviewed scientific methods. Remembering that correlation does not imply causation and that observational study does not serve to demonstrate a causal link.

Only after having this data can we say 3 things:

1. What are the harms of each type of hate speech.
2. What are the harms of suppressing hate speech (or do you think keeping people in Plato's cave of wonderland where everyone loves each other and no one can express devastating feelings is the utopia of a no-consequence scenario?)
3. How can we effectively detect and stop the spread of hate speech?

**Comment by ValZapod** [comment]
>is defending Stalin hate speech

What do you mean by defending? The guy is dead. If you mean arguing history then that is not hate speech, as that is covered by political clauses. Or you mean like the Hitler personality cult? Well, I dunno whether anyone is at the level of Hitler here for cancel culture levels, like Ye taken out of context stuff.

>Is defending Christianity hate speech?

What is there to defend? How can you defend a religion? Or you mean defending pedos there? But that is not hate speech either, protecting pedos in not something tolerated whatsover, it is above hate speach. Also where is the hate part here, just as in Hitler example?

Hate speech is on the state level of USA is things like n-word, maybe some Hitler stuff. That is kinda it (what was prosecuted).

**Comment by arian65** [comment]
Cringe

**Comment by PaulNewton** [comment]
> @satmuts  there is no such thing "hate speech"

If there is no such thing then it cannot be protected by the 1st amendment in the USA.

> @darkdevildeath First, we need to reach a formal consensus on the definition of hate speech as this is controversial.

A formal definition is elusive for something so varied that's why it's so easy to spread and harder to contain and improbable to automate against algorithmically.

It's more of a diagnostic process.

First tier is by the direct laws of the lands.
For the USA hate speech can only be criminalized when it directly incites imminent criminal activity or consists of specific threats of violence targeted against a person or group and then it's not just about freedom of speech it's a category of criminal motivation: hate crime.
Meanwhile Germany may have a a different set of rules for online speech
https://www.nytimes.com/2022/09/23/technology/germany-internet-speech-arrest.html 

Which should already be covered by policies against crime and violence but still serves as qualifier.

So either a system use the business legal requirements, a common denominator that sides with caution of one country for all users, or for all users, or a demographic majority informs with land is used for all users, or the users get their countries laws.
Though none of that comes close to making up for the broad vagueness people talking can create.


Second tier is the indirect laws of the lands , a parent category, in this case: hate crimes.
In the USA at the federal level, hate crime laws include crimes committed on the basis of the victim’s perceived or actual race, color, religion, national origin, sexual orientation, gender, gender identity, or disability.
https://www.justice.gov/hatecrimes/learn-about-hate-crimes

Again should be covered by policies against crime and violence but still serves as qualifier.

3rd tier platform ecosystem , is where it starts to get blurry and moderation has to start having influence to maintain an ecosystem treating hate speech as a precursor requiring intervention before the escalation of crimes using the platform itself for that purpose by individuals or coordination.
https://www.un.org/en/hate-speech/understanding-hate-speech/hate-speech-and-real-harm
https://press.un.org/en/2019/pi2264.doc.htm

Fourth tier, though secretly always with the first tier because of local laws, is the business requirements.
Hate speech is bad for a businesses social acceptability unless it's in the business of hate speech.

Fifth tier, local culture group. There may be phrases, in-words and language that a strict hate-speech sentiment would flag that are perfectly acceptable amongst peers of that group normally used against them by others as hate speech. Not to be confused with groups that spread hate speech amongst themselves as bigotry against others not in the group. Though it will be confused as groups that spread hate speech will seek to adopt acceptability in order to spread hate speech.

**Comment by ValZapod** [comment]
>If there is no such thing then it cannot be protected by the 1st amendment in the USA.

False. Supreme court says that hate speech is legal, free spech. Only on a state level prosecutions happened. And only because it was not overturned every time by the supreme court cause it is million of dollars in legal fees.

**Comment by 0xEbrahim** [comment]
Nice one
