### ISSUE TITLE
Add 'how to build' section in project's documentation file

### ISSUE THREAD

**Issue by tronez** [twitter/the-algorithm#861]

**Comment by BIEMAX** [comment]
Hi,

Can you provide more information on what exactly do you want? The code have a lot of components and different ways to build. I think that we have a important step before it, that is document the configurations before build. I think we have a lot of work todo, that's why it's important to have a better description in issue.

Regards,

**Comment by nobodyindustries** [comment]
@tronez the code is incomplete, it won't compile.

**Comment by impoverishedowl** [comment]
Hello, we will not reveal such trade secrets in our repository. Can you consider working at twitter if you want to go more in depth? Send an email to Twitter support and we'll figure something out. I would like to mention that you won't be paid for the first year though, as we need to see if you are a good fit for our working environment.

We appreciate your understanding, thank you!

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
