### ISSUE TITLE
Staying Focused on Scala: Why It's the Right Choice for Our Project

### ISSUE THREAD

**Issue by benatkin** [twitter/the-algorithm#87]
Hey y'all, I hate to be the party pooper, but can we get back on track here? I see a whole lotta talk 'bout rewritin' the codebase in Rust or assembly, but let's not forget about Scala! It's a powerful language that's designed to be concise, expressive, and scalable - perfect for this project. So before we start talkin' 'bout rewrite this and rewrite that, how 'bout someone explains what Scala is and why we're using it in the first place? Let's give it the attention it deserves, y'all!

**Comment by InFTord** [comment]
🤓

**Comment by Hoodgail** [comment]
> Hey y'all, I hate to be the party pooper, but can we get back on track here? I see a whole lotta talk 'bout rewritin' the codebase in Rust or assembly, but let's not forget about Scala! It's a powerful language that's designed to be concise, expressive, and scalable - perfect for this project. So before we start talkin' 'bout rewrite this and rewrite that, how 'bout someone explains what Scala is and why we're using it in the first place? Let's give it the attention it deserves, y'all!


1. Complex Syntax: Scala has a more complicated syntax than Java, making it difficult for beginners to learn and understand.

2. Lack of Libraries: Although Scala is growing in popularity, there is still a lack of libraries and frameworks available compared to languages like Java and Python.

3. Expensive: Scala is more expensive to use than Java and other popular languages, due to the need for specialized skills and tools.

4. Performance: Scala is not as fast or performant as some other languages, such as Java and C.

5. Steep Learning Curve: Scala has a steep learning curve, which can be difficult for beginners to overcome.

**Comment by no-identd** [comment]
@Hoodgail Scala 3 dissolves those points in something far, FAR away from the middle of the pH scale. And the majority of those points seem like FUD anyway. I truly hate Scala 2 on a visceral level, but consider Scala 3 a LOVELY language.
